feat: add loongarch64 platform support
Signed-off-by: 吴小白 <296015668@qq.com>
(cherry picked from commit 2590cced9863bea36e2f4ce6c31d8da5cc4da03f)

diff --git a/tools/package-denial-deb b/tools/package-denial-deb
--- a/tools/package-denial-deb
+++ b/tools/package-denial-deb
@@ -10,6 +10,10 @@ STAGE_ROOT="${DENIAL_PACKAGE_STAGE_ROOT:-$PACKAGE_INPUT_ROOT/native}"
 PACKAGE_ROOT="${DENIAL_PC_PACKAGE_ROOT:-$BUILD_ROOT/packages}"
 WORK_ROOT="${DENIAL_PC_DEB_ROOT:-$BUILD_ROOT/debian-package}"
 PACKAGER="${DENIAL_PACKAGE_PACKAGER:-Doctor Logix <doctor.logix@gmail.com>}"
+PACKAGE_ARCH="${DENIAL_PACKAGE_DEBIAN_ARCH:-$(dpkg --print-architecture)}"
+
+[[ "$PACKAGE_ARCH" =~ ^[a-z0-9][a-z0-9+.-]+$ ]] \
+  || { printf 'package-denial-deb: invalid Debian architecture: %s\n' "$PACKAGE_ARCH" >&2; exit 1; }
 
 if [[ "${DENIAL_PROMOTION_MODE:-0}" == 1 \
   && "${DENIAL_PACKAGE_SKIP_STAGE:-0}" != 1 ]]; then
@@ -63,7 +67,7 @@ build_deb() {
   {
     printf 'Package: %s\n' "$package_name"
     printf 'Version: %s-%s\n' "$PACKAGE_VERSION" "$PACKAGE_RELEASE"
-    printf 'Architecture: amd64\n'
+    printf 'Architecture: %s\n' "$PACKAGE_ARCH"
     printf 'Maintainer: %s\n' "$PACKAGER"
     printf 'Installed-Size: %s\n' "$installed_size"
     printf '%s\n' "$control_body"
@@ -75,8 +79,8 @@ build_deb() {
       --build "$package_root" "$output"
 }
 
-engine_package="$PACKAGE_ROOT/denial-flutter-engine_${PACKAGE_VERSION}-${PACKAGE_RELEASE}_amd64.deb"
-denial_package="$PACKAGE_ROOT/denial_${PACKAGE_VERSION}-${PACKAGE_RELEASE}_amd64.deb"
+engine_package="$PACKAGE_ROOT/denial-flutter-engine_${PACKAGE_VERSION}-${PACKAGE_RELEASE}_${PACKAGE_ARCH}.deb"
+denial_package="$PACKAGE_ROOT/denial_${PACKAGE_VERSION}-${PACKAGE_RELEASE}_${PACKAGE_ARCH}.deb"
 
 engine_control="$(cat <<EOF
 Section: libs
@@ -123,7 +127,7 @@ installed_size="$(du -sk --apparent-size "$STAGE_ROOT/denial" | cut -f1)"
 {
   printf 'Package: denial\n'
   printf 'Version: %s-%s\n' "$PACKAGE_VERSION" "$PACKAGE_RELEASE"
-  printf 'Architecture: amd64\n'
+  printf 'Architecture: %s\n' "$PACKAGE_ARCH"
   printf 'Maintainer: %s\n' "$PACKAGER"
   printf 'Installed-Size: %s\n' "$installed_size"
   printf '%s\n' "$denial_control"
